name: Build RA2Snes (macOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          brew update
          brew install cmake qt libva

      - name: Compile rcheevos
        run: |
          cd RA2Snes/rcheevos/test
          make ARCH=x64 BUILD=c89 CC=gcc test

      - name: Setup with CMake
        run: |
          cd RA2Snes
          cmake -S . -B build -DCMake_PREFIX_PATH=/usr/local/opt/qt/lib/cmake/Qt6

      - name: Build Project
        run: |
          cmake --build build --config Release
