name: Build RA2Snes (Windows)

on: [push, pull_request, workflow_dispatch]

jobs:
  windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt 6.9.1 (MinGW)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'

      - name: Set up MSYS2 / MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            make

      - name: Build rcheevos
        shell: msys2 {0}
        run: |
          cd rcheevos/test
          make ARCH=x64 BUILD=c89 CC=gcc HAVE_HASH=0 test
          cd ../..

      - name: Build miniz
        shell: msys2 {0}
        run: |
          cd miniz
          gcc -c miniz.c -o miniz.o
          cd ..

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        shell: bash
        run: cmake --build build --config Release

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            build/ra2snes.exe
            build/updater.exe
