name: Build RA2Snes (Linux)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qt6-tools-dev qt6-websockets-dev \
          qml6-module-qtquick qml6-module-qtquick-controls qml6-module-qtquick-layouts \
          qml6-module-qtquick-templates qml6-module-qtquick-window qt6-declarative-dev \
          qml6-module-qtqml-workerscript qml6-module-qtmultimedia qml6-module-qt-labs-folderlistmodel \
          libqt6svg6 qml6-module-qtquick-effects libva-dev libva-glx2 libva-drm2

      - name: Compile rcheevos
        run: |
          cd RA2Snes/rcheevos/test
          make ARCH=x64 BUILD=c89 CC=gcc test

      - name: Setup with CMake
        run: |
          cd RA2Snes
          cmake -S . -B build -DCMake_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6

      - name: Build Project
        run: |
          cmake --build build --config Release
