name: Build RA2Snes (Windows MSVC)

on: [push, pull_request, workflow_dispatch]

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt 6.9.1 (MSVC 2022)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtwebsockets'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build rcheevos (MSVC)
        run: msbuild.exe rcheevos-test.sln -t:rcheevos-test -p:Configuration=Release -p:Platform=x64
        working-directory: rcheevos/test

      - name: Build miniz
        shell: cmd
        run: |
          cd miniz
          cl /c miniz.c /Feminz.obj
          lib miniz.obj /OUT:miniz.lib
          cd ..

      - name: Configure CMake (MSVC)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build project (MSVC)
        run: cmake --build build --config Release

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc-build
          path: |
            build/Release/ra2snes.exe
            build/Release/updater.exe
