name: Build RA2Snes

on: [push, pull_request, workflow_dispatch]

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Upgrade to Ubuntu 24.10
      run: |
        sudo sed -i 's/jammy/mantic/' /etc/apt/sources.list
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
        sudo do-release-upgrade -f DistUpgradeViewNonInteractive    

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt6-tools-dev qt6-websockets-dev \
        qml6-module-qtquick qml6-module-qtquick-controls qml6-module-qtquick-layouts \
        qml6-module-qtquick-templates qml6-module-qtquick-window qt6-declarative-dev \
        qml6-module-qtqml-workerscript qml6-module-qtmultimedia qml6-module-qt-labs-folderlistmodel \
        libqt6svg6 qml6-module-qtquick-effects libva-dev libva-glx2 libva-drm2

    - name: Build rcheevos
      run: make ARCH=x64 BUILD=c89 CFLAGS='-Wno-unused-but-set-variable' test
      working-directory: rcheevos/test

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6

    - name: Build project
      run: cmake --build build --config Release

  macos-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        brew update
        brew install cmake qt

    - name: Build rcheevos
      run: make ARCH=x64 BUILD=c89 CFLAGS='-Wno-unused-but-set-variable' test
      working-directory: rcheevos/test

    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_PREFIX_PATH="$(brew --prefix qt)/lib/cmake/Qt6"

    - name: Build project
      run: cmake --build build --config Release
