name: Build RA2Snes

on: [push, pull_request, workflow_dispatch]

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install -y build-essential cmake qt6-tools-dev qt6-websockets-dev \
        qml6-module-qtquick qml6-module-qtquick-controls qml6-module-qtquick-layouts \
        qml6-module-qtquick-templates qml6-module-qtquick-window qt6-declarative-dev \
        qml6-module-qtqml-workerscript qml6-module-qtmultimedia qml6-module-qt-labs-folderlistmodel \
        qml6-module-qt5compat-graphicaleffects libqt6svg6

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6

    - name: Build project
      run: cmake --build build --config Release

    - name: Upload Linux Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: |
          build/ra2snes
          build/updater

  macos-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        brew install qt
        brew update
        
    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_PREFIX_PATH="$(brew --prefix qt)/lib/cmake/Qt6"

    - name: Build project
      run: cmake --build build --config Release

    - name: Create dmg
      run: |
        export PATH="/opt/homebrew/Cellar/qt/6*/bin:$PATH"
        cd build
        cp updater ra2snes.app/Contents/MacOS
        macdeployqt6 ra2snes.app -dmg
  
    - name: Upload macOS Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          build/ra2snes.dmg
  windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt 6.9.1 (MSVC 2022)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtwebsockets'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            build/Release/ra2snes.exe
            build/Release/updater.exe
