name: CMake Build

on: [push, pull_request]

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
       sudo apt-get update && sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools qt6-translations-l10n libqt6websockets6-dev qt6-declarative-dev gcc-multilib # bits/libc-header-start.h
    - name: Build rcheevos
      run: make ARCH=x64 BUILD=c89 test
      working-directory: rcheevos/test
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6
    - name: Build project
      run: cmake --build build --config Release
      
  windows-x64:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        modules: 'qtwebsockets'
    - name: Install dependencies
      run: |
        choco install -y cmake
        choco install -y make
        choco install -y vulkan-sdk --version=1.3.250.0
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Set Vulkan environment variables
      run: |
        echo "VULKAN_SDK=C:\\VulkanSDK\\1.3.250.0" >> $env:GITHUB_ENV
        echo "C:\\VulkanSDK\\1.3.250.0\\Bin" >> $env:GITHUB_PATH
        echo "C:\\VulkanSDK\\1.3.250.0\\Lib" >> $env:GITHUB_PATH
        echo "C:\\VulkanSDK\\1.3.250.0\\Include" >> $env:GITHUB_PATH
      shell: pwsh
    - name: Build rcheevos
      run: msbuild.exe rcheevos-test.sln -t:rcheevos-test -p:Configuration=Release -p:Platform=x64
      working-directory: rcheevos/test
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build project
      run: cmake --build build --config Release

      
